default: &default
  adapter: postgresql
  username: postgres
  host: localhost
  password: postgres
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: mihatechSolutions
test:
  <<: *default
  database: mihatechSolutions

production:
  <<: *default
  database: mihatechSolutions
