default: &default
  adapter: postgresql
  username: postgres
  host: localhost
  password: postgres
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: mihatech
test:
  <<: *default
  database: mihatech

production:
  <<: *default
  database: mihatech
